task: "ccr_jp_full"
test_split: test
include: _default_template_yaml
dataset_kwargs:
  data_files:
    test: /raid/ASR/asr-ja-eval-datasets/ccr_202306_disc1_phase1_200_calls/full_audios_manifest.jsonl
  field: null
